CREATE TABLE IF NOT EXISTS `serious-game`.`severities` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `severity` TINYINT(4) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;